# version: "3.8"

# services:
#   postgres:
#     image: postgres:15
#     container_name: kanban-postgres
#     environment:
#       POSTGRES_DB: kanbandb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - kanban_pgdata:/var/lib/postgresql/data

#   backend:
#     build: ./backend
#     container_name: kanban-backend
#     ports:
#       - "8085:8085"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kanbandb
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: postgres
#       SERVER_PORT: 8085
#     depends_on:
#       - postgres

#   frontend:
#     build:
#       context: ./frontend
#     container_name: kanban-frontend
#     ports:
#       - "3001:80"
#     depends_on:
#       - backend

# volumes:
#   kanban_pgdata:


version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: kanban-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - kanban_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: kanban-backend
    env_file:
      - .env
    ports:
      - "8085:8085"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: kanban-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  kanban_pgdata:
